dotnet/machinelearning-samples

- samples/getting-started/MulticlassClassification_Iris/README.md
Order of lines is incorrect. А variable is used before it was declared.
> This fixes invalid code snippet in the README

- samples/examples/Reggression_BikeSharingDemands/BikeSharingDemand/BikeSharingDemand.csproj
Upgraded Reggression_BikeSharingDemands sample to ML.NET v0.3 or any version which is globally specified with $(MicrosoftMLVersion) from the global Directory.Build.props file.
> Upgraded Reggression_BikeSharingDemands sample to v0.3 of vNext globally specified

- CONTRIBUTING.md
Remove redundant Contributing section in CONTRIBUTING.md containing a broken link.
Closes #50
> Remove redundant Contributing section in CONTRIBUTING.md

- samples/csharp/getting-started/Regression_TaxiFarePrediction/README.md
Fix broken image in https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/Regression_TaxiFarePrediction
> Fix Broken Image in Regression_TaxiFarePrediction README.md

- samples/csharp/examples/DeepLearning_TensorFlowMLNETInceptionv3ModelScoring/Program.cs
Fixing Issue #53 to be able to execute tensorflow sample over 0.6.0 ML.NET version.
Loading Assemblies ImageAnalytics and TensorFlowTransform
> Cannot execute tensorflow scoring samples 

- samples/csharp/getting-started/BinaryClasification_Titanic/BinaryClasification_TitanicSurvivalPrediction/Program.cs
- samples/csharp/getting-started/BinaryClasification_Titanic/BinaryClasification_TitanicSurvivalPrediction/TestTitanicData.cs
- samples/csharp/getting-started/BinaryClasification_Titanic/BinaryClasification_TitanicSurvivalPrediction/TitanicData.cs
- samples/csharp/getting-started/Clustering_CustomerSegmentation/CustomerSegmentation.Train/ModelBuilder/ModelBuilder.cs
- samples/csharp/getting-started/Regression_TaxiFarePrediction/Program.cs
Related to #81.
Improved the following samples:
* Removed PCA seed
* Removed LossFn
* Improved metrics:
Before:
- R2 Score: 0.58
- RMS loss: 7.03
- Absolute loss: 2.02
After:
- R2 Score: 0.7
- RMS loss: 5.97
- Absolute loss: .99
Improved features and learner:
- Default params for fasttree
- Fare -> numeric
- Improved transformation of categorical features 
Metrics before:
- Accuracy: 80.85 %
- Auc: 82.27 %
- F1Score: 67.47 %
Metrics after:
- Accuracy: 85.11 %
- Auc: 87.47 %
- F1Score: 79.21 %
> DS Review: Improved three samples

- samples/fsharp/getting-started/MulticlassClassification_Iris/MulticlassClassification_Iris.fsproj
- samples/fsharp/getting-started/MulticlassClassification_Iris/Program.fs
- samples/fsharp/getting-started/MulticlassClassification_Iris/README.md
Migration done by following C# sample.
Continued with Pipeline module introduced with `BinaryClassification_SentimentAnalysis` sample, which is supposed to make some operations on pipeline more F# friendly. This allows to pipe operations for creating pipeline and training model (idea is similar to Seq/List/Array modules which allow to pipe chain methods):
```fsharp
let model = 
env
|> Pipeline.concatEstimator "Features" [| "SepalLength"; "SepalWidth"; "PetalLength"; "PetalWidth" |]
|> Pipeline.append (SdcaMultiClassTrainer(env, SdcaMultiClassTrainer.Arguments(), "Features", "Label"))
|> Pipeline.fit trainingDataView
```
For now I copied file from `BinaryClassification_SentimentAnalysis` sample and added `concatEstimator` function, but I am thinking about moving it outside and share …
> #83 Moved MulticlassClassification_Iris F# sample to new dynamic API.

- samples/fsharp/getting-started/Clustering_Iris/Clustering_Iris.fsproj
- samples/fsharp/getting-started/Clustering_Iris/Program.fs
- samples/fsharp/getting-started/Clustering_Iris/README.md
Migration done by following C# sample.
Continued with Pipeline module introduced with BinaryClassification_SentimentAnalysis sample, which is supposed to make some operations on pipeline more F# friendly. This allows to pipe operations for creating pipeline and training model (idea is similar to Seq/List/Array modules which allow to pipe chain methods):
```fsharp
let model = 
env
|> Pipeline.concatEstimator "Features" [| "SepalLength"; "SepalWidth"; "PetalLength"; "PetalWidth" |]
|> Pipeline.append (KMeansPlusPlusTrainer(env, "Features", clustersCount = 3))
|> Pipeline.fit trainingDataView
```
For now I copied file from BinaryClassification_SentimentAnalysis sample and added concatEstimator function, but I am thinking about moving it outside and share between projects.
Applied code style …
> #83 Moved Clustering_Iris F# sample to new dynamic API. 

- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Trainer/ModelBuilder.cs
'test' data was saved in place of 'train' data.
> Fix model builder

- README.md
- samples/fsharp/getting-started/BinaryClassification_SpamDetection/README.md
- samples/fsharp/getting-started/BinaryClassification_SpamDetection/SpamDetectionConsoleApp/Data/spamfolder/SMSSpamCollection
- samples/fsharp/getting-started/BinaryClassification_SpamDetection/SpamDetectionConsoleApp/Data/spamfolder/readme
- samples/fsharp/getting-started/BinaryClassification_SpamDetection/SpamDetectionConsoleApp/Program.fs
- samples/fsharp/getting-started/BinaryClassification_SpamDetection/SpamDetectionConsoleApp/SpamDetectionConsoleApp.fsproj
- samples/fsharp/v0.9-All-Samples.sln
Unlike the C# sample this does not use a custom mapping partly due to https://github.com/dotnet/machinelearning/issues/2422.
> spam detection sample ported to F#

- samples/csharp/common/ConsoleHelper.cs
- samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/Program.cs
- samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/SentimentAnalysis/SentimentAnalysisConsoleApp/Program.cs
- samples/csharp/getting-started/Clustering_CustomerSegmentation/CustomerSegmentation.Train/Program.cs
- samples/csharp/getting-started/Clustering_Iris/IrisClustering/IrisClusteringConsoleApp/Program.cs
- samples/csharp/getting-started/MulticlassClassification_HeartDisease/HeartDiseaseConsoleApp/Program.cs
- samples/csharp/getting-started/Regression_BikeSharingDemand/BikeSharingDemand/BikeSharingDemandConsoleApp/Program.cs
- samples/csharp/getting-started/Regression_TaxiFarePrediction/TaxiFarePrediction/TaxiFarePredictionConsoleApp/Program.cs
Updated consolehelper.PeekViewToConsole() method to use preview().
List of samples which have ConsoleHelper.PeekViewToConsol():
1. BikeSharingDemand
2. Customer Segmentation
3. Git Hub Labeler
4. IRIS Clustering
5. TaxiFare Prediction
6. Heart Disease
7. Sentiment Analysis
> Update PeekViewToConsole method to to use Preview()

- samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/Program.cs
The input isn't sparse, but the ReadFromTextFile is using the default of
supportSparse=true, which is causing the loader to try and fail to parse
every row as if it were sparse (you can see this if you hook up an
mlcontext.Log handler and print out every message containing "Format").
Related to https://github.com/dotnet/machinelearning/issues/2576
cc: @CESARDELATORRE, @eerhardt
> Turn off supportSparse in GitHubLabeler sample

- samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/DataStructures/FullPrediction.cs
- samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/DataStructures/GitHubIssuePrediction.cs
- samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/Labeler.cs
- samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/Program.cs
1.Created a class to have Prediction values like score, label and matchingSchemaIndex
2.Added Score filed in GitHubIssuePrediction class.
3.Changed the existing code like ApplyingLabels,PredictLabels in Labeler class.
4.Added new method in Labeler class to find the best 3 scores and return their indexes so that we can get the labels of those matched indexes from slotnames.
> Upgrade :Classify github issues into the best 3 labels instead of one label

- samples/fsharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Train/assets/outputs/README.txt
output directory needs to exist for tensorflow estimator sample. #264
> create output directory for F# tensorflow estimator sample

- README.md
Just noticed my last update was duplicating icons. This just removes the extra getting-started/end-to-end icon to be consistent with the other links.
> Remove duplicate icons for C#/F# samples

- samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/Program.cs
Reverts dotnet/machinelearning-samples#257
This is no longer needed, as:
- https://github.com/dotnet/machinelearning/pull/2630 made supportSparse default to false.  And even if it wasn't changed....
- https://github.com/dotnet/machinelearning/pull/2579 made supportSparse faster when it is true, in particular when the debugger is attached.
cc: @CESARDELATORRE
> Revert "Turn off supportSparse in GitHubLabeler sample"

- samples/csharp/getting-started/Regression_TaxiFarePrediction/README.md
This change is consistent with the actual sample code - I guess there was an API change at some point renaming the method from `ReadFromTextFile` to `LoadFromTextFile`.
> Replace TaxiFarePrediction README's use of `ReadFromTextFile` with `LoadFromTextFile`

- samples/csharp/getting-started/MulticlassClassification_mnist/mnist/Program.cs
This addresses issue #368. By default `MapValueToKey` uses first occurrence ordering of keys where the sample output is assuming value ordering.
> Fix key ordering in mnist sample

- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI-IntegrationPkg/README.md
- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/README.md
- samples/csharp/end-to-end-apps/ScalableSentimentAnalysisBlazorWebApp/README.md
Noticed a few typos in some of the readme files while looking at the examples.
> Fixed typos in documentation

- samples/csharp/end-to-end-apps/Regression-SalesForecast/src/eShopForecastModelsTrainer/Program.cs
- samples/csharp/getting-started/Clustering_CustomerSegmentation/CustomerSegmentation.Predict/Program.cs
- samples/csharp/getting-started/Clustering_CustomerSegmentation/CustomerSegmentation.Train/Program.cs
- samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow/ImageClassification/Program.cs
- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/Program.cs
- samples/csharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Predict/Program.cs
- samples/csharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Train/Program.cs
- samples/csharp/getting-started/MulticlassClassification_MNIST/MNIST/Program.cs
- samples/fsharp/getting-started/Clustering_CustomerSegmentation/CustomerSegmentation.Predict/Program.fs
- samples/fsharp/getting-started/Clustering_CustomerSegmentation/CustomerSegmentation.Train/Program.fs
- samples/fsharp/getting-started/DeepLearning_ImageClassification_TensorFlow/ImageClassification/Program.fs
- samples/fsharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/Program.fs
- samples/fsharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Predict/Program.fs
- samples/fsharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Train/Program.fs
Hi!
Thanks for the samples! The first thing I ran into, is only the exception's `Message` is logged or written to console. But that's not always enough. InnerException and Stacktrace helps a lot. For example:
```
EXCEPTION
#########
Splitter/consolidator worker encountered exception while consuming source data
```
There was a typo in the filename:
```
EXCEPTION
#########
System.InvalidOperationException: Splitter/consolidator worker encountered exception while consuming source data
---> System.InvalidOperationException: Image xtoaster2.png was not found.
```
Or 
```
EXCEPTION
#########
Index was outside the bounds of the array.
```
Stacktrace helps, checked the code at that line, and found the reason:
```
EXCEPTION
#########
System.IndexOutOfRangeException: Index was outside the bounds of …
```
> Log Exception.ToString() instead of Exception.Message

- samples/csharp/end-to-end-apps/AnomalyDetection-Sales/README.md
Link to csv data in readme was not working.
> Update link path to csv data in README for SpikeDetectionE2EApp

- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/DataStructures/ImageNetData.cs
- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/DataStructures/ImageNetPrediction.cs
- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/OnnxModelScorer.cs
- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/Program.cs
- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/YoloParser/YoloBoundingBox.cs
- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/YoloParser/YoloOutputParser.cs
- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/YoloParser/YoloWinMlParser.cs
Refactored sample to improve flow / readability
List of Changes
1. Renamed `YoloWinMlParser` to `YoloOutputParser`.
2. Fixed namespaces on classes within subdirectories to match their location in the project structure.
4. Changed return type of `LoadModel` method to `ITransformer`
3. Removed `CreateEmptyDataView` since it is only used once and replaced it with `_mlContext.Data.LoadFromEnumerable(new List<ImageNetData>());` inside of `LoadModel` method.
4. Changed `PredictDataUsingModel` method signature to decouple post-processing steps.
5. Use `Transform` method instead of `PredictionEngine` to score data using the model in `PredictDataUsingModel` method.
6. Updated `Score` method to reflect changes in other helper methods.
7. Removed `GetImagesData` method. Moved logic to `ImageNetData` …
> Improve ONNX Object Detection Flow

- modelbuilder/readme.md
According to [Announcing ML.NET 1.2 and Model Builder updates ](https://devblogs.microsoft.com/dotnet/announcing-ml-net-1-2-and-model-builder-updates-machine-learning-for-net/), the limit on training data size has been removed.
> Remove limitation on training data size

- samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow/README.md
- Adjusted indentation in model snippet
- Adjusted chained method call indentation in pipeline definition snippet
- Added missing code snippet with constants used in pipeline definition
Both adjustments are for readability, the missing code snippet is necessary as they are not defined anywhere else and are used in the pipeline creation. I've taken them from https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification#create-a-struct-for-default-parameters since both articles are using the same inception model.
> Code readability adjustments and missing constants

- samples/csharp/end-to-end-apps/Forecasting-Sales/README.md
The backslash was being Url encoded which broke the link. Changing it to a forward slash.
> Fix broken link

- samples/csharp/end-to-end-apps/ScalableSentimentAnalysisBlazorWebApp/BlazorSentimentAnalysis.Server/BlazorSentimentAnalysis.Server.csproj
the csproj files for the blazor sentiment analysis demo were broken post-3.0 release. this pr updates those .csproj files so the app will work under the 3.0 GA SDK.
> updated blazor-related csproj files

- samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/.gitignore
- samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/DeepLearning_ImageClassification_Binary/DeepLearning_ImageClassification_Binary.csproj
- samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/DeepLearning_ImageClassification_Binary/Program.cs
- samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/DeepLearning_ImageClassification_Binary/workspace/README.md
- samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/README.md
- Updated preprocessing pipeline to use `LoadRawImageBytes`.
- Updated training pipeline to use `ImageClassificationTrainer.Options` to set parameters.
To-do:
> Update Image Classification Sample to 1.4

- samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/DeepLearning_ImageClassification_Binary/DeepLearning_ImageClassification_Binary.csproj
- samples/csharp/getting-started/Forecasting_BikeSharingDemand/BikeDemandForecasting/BikeDemandForecasting.csproj
Updated samples that are used in Docs tutorials.
- Bike Sharing Demand
- Image Classification API
> Update API tutorials to v 1.5

- samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/DeepLearning_ImageClassification/DeepLearning_ImageClassification.csproj
- samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/DeepLearning_ImageClassification/Program.cs
- samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/README.md
This `DeepLearning_ImageClassification_Binary` sample requires that `assets.zip` be first unpacked into its intended `\assets` destination.
In addition, the `WorkspacePath` given to the `ImageClassification.Options` to indicates the path where the TensorFlow image bottleneck cache files and trained model are saved may be a path longer than 255 chars, which is [the maximum path length supported by the Windows shell ](https://stackoverflow.com/questions/1857335/is-there-any-length-limits-of-file-path-in-ntfs). If the path is longer than this, a TF Saver errors occurs (as detailed in this [issue](https://github.com/una-dinosauria/human-motion-prediction/issues/10)) where TensorFlow's Saver.save method fails to create the checkpoint file. Given that the sample's path is already long in this …
> Minor edits to the DeepLearning Binary classification sample

- samples/Directory.Build.props
- samples/csharp/end-to-end-apps/DeepLearning_ImageClassification_TF/TFImageClassification/TFImageClassification.csproj
- samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/DeepLearning_ImageClassification/DeepLearning_ImageClassification.csproj
- samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow/ImageClassification/ImageClassification.Score.csproj
- samples/csharp/getting-started/DeepLearning_ImageClassification_Training/ImageClassification.Predict/ImageClassification.Predict.csproj
- samples/csharp/getting-started/DeepLearning_ImageClassification_Training/ImageClassification.Train/ImageClassification.Train.csproj
- samples/csharp/getting-started/DeepLearning_ImageClassification_Training/WebApp.Predict/ImageClassification.WebApp.csproj
- samples/csharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Predict/ImageClassification.Predict.csproj
- samples/csharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Train/ImageClassification.Train.csproj
- samples/fsharp/getting-started/DeepLearning_ImageClassification_TensorFlow/ImageClassification/ImageClassification.Score.fsproj
- samples/fsharp/getting-started/DeepLearning_ImageClassification_Training/ImageClassification.Train/ImageClassification.Train.fsproj
- samples/fsharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Predict/ImageClassification.Predict.fsproj
- samples/fsharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Train/ImageClassification.Train.fsproj
1. upgrade SciSharp.TensorFlow.Redist version to 2.3.1 same as ml.net
2. fix tf not running on netcore 2.1 exception by introducing reference to "System.Runtime.CompilerServices.Unsafe" package
> fix some issues for samples repo

- samples/csharp/common/AutoML/ConsoleHelper.cs
- samples/csharp/common/AutoML/ProgressHandlers.cs
- samples/csharp/getting-started/Ranking_AutoML/Ranking/README.md
- samples/csharp/getting-started/Ranking_AutoML/Ranking/Ranking.sln
- samples/csharp/getting-started/Ranking_AutoML/Ranking/Ranking/DataStructures/RankingData.cs
- samples/csharp/getting-started/Ranking_AutoML/Ranking/Ranking/DataStructures/RankingPrediction.cs
- samples/csharp/getting-started/Ranking_AutoML/Ranking/Ranking/Program.cs
- samples/csharp/getting-started/Ranking_AutoML/Ranking/Ranking/Ranking.csproj
Add Ranking sample for AutoML.
Update for [this issue](https://github.com/dotnet/machinelearning/issues/5408)
> Add Ranking AutoML Sample

- samples/modelbuilder/ObjectDetection_StopSigns/StopSignDetection/README.md
Looking at other sample (https://github.com/dotnet/machinelearning-samples/blob/0f01ae23a204d142923fb678c5f178b10592674d/samples/modelbuilder/ImageClassification_Azure_LandUse/README.md), the value there is just `vs`.
> Update product in sample's README

- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/ObjectDetection.csproj
- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/Program.cs
- samples/csharp/getting-started/Forecasting_BikeSharingDemand/BikeDemandForecasting/BikeDemandForecasting.csproj
- samples/csharp/getting-started/Forecasting_BikeSharingDemand/BikeDemandForecasting/Program.cs
Updating tutorial samples to .NET 6
Fixes [#26334](https://github.com/dotnet/docs/issues/26334)
> Update samples to .NET 6

- samples/csharp/getting-started/DeepLearning_ImageClassification_Training/ImageClassification.Train/Program.cs
- samples/csharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Train/Program.cs
- samples/fsharp/getting-started/DeepLearning_ImageClassification_Training/ImageClassification.Train/Program.fs
Updated the flower photos sample dataset url to the correct url.
> Updated samples image url
