dotnet/machinelearning-samples

- samples/end-to-end-apps/github-labeler/GitHubLabeler/Predictor.cs
> Set useHeader parameter to true in GitHub sample

- samples/end-to-end-apps/eShopDashboardML/src/eShopDashboard/wwwroot/js/site.js
remove extra call for forecasting previous period, and update remaining code
related to issue #23
> remove redundant forecasting call

- samples/fsharp/getting-started/BinaryClassification_SentimentAnalysis/Program.fs
- samples/fsharp/getting-started/Clustering_Iris/Program.fs
- samples/fsharp/getting-started/MulticlassClassification_Iris/Program.fs
- samples/fsharp/getting-started/Regression_TaxiFarePrediction/Program.fs
> Fixed F# samples

- samples/csharp/getting-started/MulticlassClassification_Iris/README.md
Fix broken image in https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/MulticlassClassification_Iris
> Fix Broken Image in  MulticlassClassification_Iris README.md

- samples/csharp/examples/BinaryClasification_Titanic/README.md
- samples/fsharp/getting-started/BinaryClassification_SentimentAnalysis/README.md
- samples/fsharp/getting-started/MulticlassClassification_Iris/README.md
- samples/fsharp/getting-started/Regression_TaxiFarePrediction/README.md
This was still an issue on other README.fd files, like in fsharp projects. Fixed all image sources using relative path. Fixes: #47
> Fix broken image in remaining README.md files #47

- samples/csharp/examples/BinaryClasification_Titanic/BinaryClasification_TitanicSurvivalPrediction/Program.cs
- samples/csharp/examples/BinaryClasification_Titanic/BinaryClasification_TitanicSurvivalPrediction/TitanicPrediction.cs
Instead of just returning label, now returns probability score also
> added probability scores for Titanic predictions

- samples/csharp/getting-started/Regression_TaxiFarePrediction/Program.cs
- Simplification for model's type when used as parameter and reader's code extraction to a method so it is re-used.
> Refactoring and simplification for TaxiFarePrediction regression sample

- samples/csharp/getting-started/Regression_BikeSharingDemand/BikeSharingDemandConsoleApp/src/BikeSharingDemand.csproj
Simple update: BikeSharing sample: Updated to latest ML.NET 0.7-Preview NuGet package
> BikeSharing sample: Updated to latest ML.NET 0.7-Preview NuGet package

- .gitignore
- samples/fsharp/getting-started/BinaryClassification_SentimentAnalysis/Program.fs
- samples/fsharp/getting-started/Clustering_Iris/Program.fs
- samples/fsharp/getting-started/MulticlassClassification_Iris/Program.fs
- samples/fsharp/getting-started/Regression_TaxiFarePrediction/Program.fs
Very simple changes to make code more F# friendly.
> Change code for F# sample, so it looks more F# way of code

- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Trainer/ModelBuilder.cs
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Trainer/Program.cs
Removed Static API from CC-Fraud-Detection sample
> Removed Static API from CC-Fraud-Detection sample

- docs/COMMUNITY-SAMPLES.md
Added Community Samples page (ever-evolving page)
> Added Community Samples page (ever-evolving page)

- docs/DATASETS.md
PR for page to track datasets used by Samples at ML.NET Samples repo
> PR for page to track datasets used by Samples at ML.NET Samples repo

- docs/STRUCTURE-GUIDELINES.md
- docs/STYLE-GUIDELINES.md
Doc includes the following topics to discuss:
- Opinionated "Directory/folders structure" and reasons why we're recommending it
- Phases/sections for internal code to implement within a "model training/test" application
> Added Project Structure Guidelines .md document

- samples/csharp/end-to-end-apps/github-labeler/GitHubLabeler/GitHubLabelerConsoleApp/GitHubLabeler.csproj
- samples/csharp/end-to-end-apps/github-labeler/GitHubLabeler/GitHubLabelerConsoleApp/Labeler.cs
- samples/csharp/end-to-end-apps/github-labeler/GitHubLabeler/GitHubLabelerConsoleApp/Predictor.cs
- samples/csharp/end-to-end-apps/github-labeler/GitHubLabeler/GitHubLabelerConsoleApp/Program.cs
- samples/csharp/v0.7-Samples-Based-On-Common-Code.sln
Updated GitHub Labeler pipeline for v0.7-Preview.
Refactoring still work in progress
> Updated GitHub Labeler pipeline for v0.7-Preview

- samples/csharp/common/ConsoleHelper.cs
- samples/csharp/common/ModelScorer.cs
- samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/DataProcessor.cs
- samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/Program.cs
Fixing confidence Interval for CV metrics should be calculated using t-distribution quantiles
> Fixing confidence Interval for CV metrics 

- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Common/ConsoleHelpers.cs
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Common/CreditCardFraudDetection.Common.csproj
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Common/Extensions.cs
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Predictor/CreditCardFraudDetection.Predictor.csproj
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Predictor/Predictor.cs
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Trainer/CreditCardFraudDetection.Trainer.csproj
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Trainer/ModelBuilder.cs
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Trainer/Program.cs
- samples/csharp/getting-started/Regression_BikeSharingDemand/BikeSharingDemand/BikeSharingDemandConsoleApp/DataProcessor.cs
- samples/csharp/getting-started/Regression_TaxiFarePrediction/TaxiFarePrediction/TaxiFarePredictionConsoleApp/DataProcessor.cs
- samples/csharp/v0.7-Samples-Based-On-Common-Code.sln
CCFraudDetection migrated to v0.7 plus minor refactoring of other samples
>  CCFraudDetection migrated to v0.7

- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Predictor/Predictor.cs
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Predictor/Program.cs
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Trainer/ModelBuilder.cs
- samples/csharp/getting-started/Regression_TaxiFarePrediction/TaxiFarePrediction/TaxiFarePredictionConsoleApp/Program.cs
FraudDetection sample refactored not to use the BinarySaver and lower level HostEnvironment but instead the MLContext.Data.SaveAsText()
> FraudDetection sample refactored not to use the BinarySaver but MLContext.Data.SaveAsText()

- samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/Directory.Build.props
- samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/Program.cs
- samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/Directory.Build.props
- samples/csharp/end-to-end-apps/Regression-SalesForecast/Directory.Build.props
- samples/csharp/end-to-end-apps/Regression-SalesForecast/src/eShopDashboard/eShopDashboard.csproj
- samples/csharp/end-to-end-apps/Regression-SalesForecast/src/eShopForecastModelsTrainer/eShopForecastModelsTrainer.csproj
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Common/Extensions.cs
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Predictor/Predictor.cs
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Trainer/ModelBuilder.cs
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/Directory.Build.props
- samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/Directory.Build.props
- samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/SentimentAnalysis/SentimentAnalysisConsoleApp/Program.cs
- samples/csharp/getting-started/Clustering_CustomerSegmentation/CustomerSegmentation.Train/Program.cs
- samples/csharp/getting-started/Clustering_CustomerSegmentation/Directory.Build.props
- samples/csharp/getting-started/Clustering_Iris/Directory.Build.props
- samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow/Directory.Build.props
- samples/csharp/getting-started/MatrixFactorization_MovieRecommendation/Directory.Build.props
- samples/csharp/getting-started/MulticlassClassification_Iris/Directory.Build.props
- samples/csharp/getting-started/MulticlassClassification_Iris/IrisClassification/IrisClassificationConsoleApp/Program.cs
- samples/csharp/getting-started/Regression_BikeSharingDemand/Directory.Build.props
- samples/csharp/getting-started/Regression_TaxiFarePrediction/Directory.Build.props
- samples/csharp/getting-started/Regression_TaxiFarePrediction/TaxiFarePrediction/TaxiFarePredictionConsoleApp/Program.cs
- samples/csharp/v0.7-All-Samples.sln
- samples/csharp/v0.8-All-Samples.sln
Some samples updated to ML.NET v0.8-Preview (0.8.0-preview-27128-1)
Will be updated to v0.8 when released.
> Some samples updated to ML.NET v0.8-Preview

- README.md
> Add Translation Link

- docs/COMMUNITY-SAMPLES.md
Community was misspelled to I fixed it.
> Corrected Community header

- samples/csharp/common/MLModelEngine.cs
- samples/csharp/common/ObjectPool.cs
- samples/csharp/end-to-end-apps/Regression-SalesForecast/src/TestObjectPoolingConsoleApp/Program.cs
- samples/csharp/end-to-end-apps/Regression-SalesForecast/src/eShopDashboard/Startup.cs
Added expirationTime and better management for minPoolSize and maxPoolSize
> Added expirationTime and improvements to Object Pooling for PredictionEngine

- samples/csharp/getting-started/DeepLearning_TensorFlowEstimator/README.md
Update source code in `Readme.md` file.
> Update DeepLearning_TensorFlowEstimator Readme.md

- samples/fsharp/getting-started/CreditCardFraudDetection/CreditCardFraudDetection.sln
- samples/fsharp/getting-started/CreditCardFraudDetection/CreditCardFraudDetection/CreditCardFraudDetection.fsproj
- samples/fsharp/getting-started/CreditCardFraudDetection/CreditCardFraudDetection/Program.fs
Converted credit card fraud detection sample from C# to F#
> Credit card fraud detection in F#

- samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/SentimentAnalysis/SentimentAnalysisConsoleApp/Program.cs
I was reviewing and learning how to apply sentiment analysis using ML.NET with the great SentimentAnalysisConsoleApp. Noticed a couple of things that could be cleaned up and thought I could contribute.
> Minor clean-up of SentimentAnalysisConsoleApp 

- samples/fsharp/getting-started/Regression_TaxiFarePrediction/TaxiFarePrediction.sln
TaxiFarePrediction.sln had an incorrect path to TaxiFarePrediction.fsproj
> Fix TaxiFarePrediction.sln

- samples/csharp/common/ConsoleHelper.cs
- samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/SentimentAnalysis/SentimentAnalysisConsoleApp/Program.cs
This fix is done only for "Sentiment Analysis". It needs to be done or the rest of the samples
> Fixed path issue depending if running on VS or CLI

- samples/csharp/common/ConsoleHelper.cs
- samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/Program.cs
- samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender_Model/Program.cs
- samples/csharp/end-to-end-apps/Regression-SalesForecast/src/eShopForecastModelsTrainer/Program.cs
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Predictor/Program.cs
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Trainer/ModelBuilder.cs
- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection.Trainer/Program.cs
- samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/SentimentAnalysis/SentimentAnalysisConsoleApp/Program.cs
- samples/csharp/getting-started/Clustering_CustomerSegmentation/CustomerSegmentation.Predict/Program.cs
- samples/csharp/getting-started/Clustering_CustomerSegmentation/CustomerSegmentation.Train/Program.cs
- samples/csharp/getting-started/Clustering_Iris/IrisClustering/IrisClusteringConsoleApp/Program.cs
- samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow/ImageClassification/Program.cs
- samples/csharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Predict/Program.cs
- samples/csharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Train/Program.cs
- samples/csharp/getting-started/MatrixFactorization_MovieRecommendation/MovieRecommendation/DataStructures/Movie.cs
- samples/csharp/getting-started/MatrixFactorization_MovieRecommendation/MovieRecommendation/MovieRecommendation.csproj
- samples/csharp/getting-started/MatrixFactorization_MovieRecommendation/MovieRecommendation/Program.cs
- samples/csharp/getting-started/MatrixFactorization_ProductRecommendation/ProductRecommender/Program.cs
- samples/csharp/getting-started/MulticlassClassification_HeartDisease/HeartDiseaseConsoleApp/Program.cs
- samples/csharp/getting-started/MulticlassClassification_Iris/IrisClassification/IrisClassificationConsoleApp/Program.cs
- samples/csharp/getting-started/MulticlassClassification_mnist/mnist/Program.cs
- samples/csharp/getting-started/Regression_BikeSharingDemand/BikeSharingDemand/BikeSharingDemandConsoleApp/Program.cs
- samples/csharp/getting-started/Regression_TaxiFarePrediction/TaxiFarePrediction/TaxiFarePredictionConsoleApp/Program.cs
Fixed path issue by getting the assembly path of the sample and then going to the data folder from the assembly path.
All the samples are fixed with the fix except spam detection as its already having same kind of code.
> Fix Path Issue depending on if running on CLI or visual studio

- samples/fsharp/getting-started/BinaryClassification_CreditCardFraudDetection/CreditCardFraudDetection/Program.fs
Was only showing 2 decimal places now set to 12
> #263 F# print more digits for accuracy in credit card fraud sample

- samples/fsharp/getting-started/DeepLearning_ImageClassification_TensorFlow/ImageClassification/Program.fs
> 6 to 7 decimal places for prob in F# TensorFlow Scorer #266

- samples/fsharp/common/ConsoleHelper.fs
- samples/fsharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/DataStructures/DataStructures.fs
- samples/fsharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/GitHubLabeler.fsproj
- samples/fsharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/Labeler.fs
- samples/fsharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/Program.fs
Update github labeler sample to 0.1 and off of Helpers. Addresses #265
> update GITHUB Labeler sample

- samples/fsharp/getting-started/BinaryClassification_SpamDetection/SpamDetectionConsoleApp/Program.fs
> F# - print spam or not spam

- samples/fsharp/common/ConsoleHelper.fs
- samples/fsharp/getting-started/Regression_BikeSharingDemand/BikeSharingDemand/BikeSharingDemandConsoleApp/Program.fs
Also a couple of very small console output changes to match C# samples.
> F# - WorkingDay was missing from feature set for Bike sample

- samples/csharp/v0.11-All-Samples.sln
- samples/fsharp/getting-started/Regression_BikeSharingDemand/BikeSharingDemand/BikeSharingDemandConsoleApp/ModelScoringTester.fs
It's the same fix than for issue https://github.com/dotnet/machinelearning-samples/issues/227 but on F# side.
> Use culture when parsing a string to a float32

- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/README.md
- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/ScalableMLModelOnWebAPI.sln
- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/src/Scalable.Model/DataModels/SampleObservation.cs
- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/src/Scalable.Model/DataModels/SamplePrediction.cs
- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/src/Scalable.Model/Engine/MLModelEngine.cs
- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/src/Scalable.Model/Engine/PooledPredictionEnginePolicy.cs
- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/src/Scalable.Model/Scalable.Model.csproj
- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/src/Scalable.WebAPI/Controllers/PredictorController.cs
- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/src/Scalable.WebAPI/Program.cs
- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/src/Scalable.WebAPI/Scalable.WebAPI.csproj
- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/src/Scalable.WebAPI/Startup.cs
- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/src/Scalable.WebAPI/appsettings.Development.json
- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/src/Scalable.WebAPI/appsettings.json
ASP.NET Core 2.2 WebAPI sample optimized for scalability and performance when runnig/scoring an ML.NET model.
> WebAPI sample optimized for scalability and performance when runnig/scoring an ML.NET model

- samples/csharp/end-to-end-apps/AnomalyDetection-ShampooSales-WinForms/AnomalyDetectionConsoleApp/Program.cs
Fixed minor typos in the new anomaly detection end-2-end solution.
> Fixed minor typos

- samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection/Readme.md
Fix type-o in readme: 'speccifying' => 'specifying'.
> Fix type-o in readme: 'speccifying' => 'specifying'

- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/src/Scalable.WebAPI/Properties/launchSettings.json
Scalable WebAPI: Added launchSettings.json to git so sample works out-of-the-box with test data
> Scalable WebAPI: Added launchSettings.json to git so sample works out-of-the-box with test data 

- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI-IntegrationPkg/src/Scalable.WebAPI/Properties/launchSettings.json
- samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI/src/Scalable.WebAPI/Properties/launchSettings.json
Minor URL settings so it works out-of-the-box
> Minor Scalable.WebAPI changes

- samples/csharp/getting-started/Clustering_CustomerSegmentation/README.md
First I thought it was such a small thing I wasn't going to mention it, but then I thought maybe everyone thinks like that so just wanted to let you know.
> Comment was missing forward slash

- modelbuilder/readme.md
#418
You can put the link where you're comfortable, I just think it should be somewhere.
> Add link to the ML Builder extension page

- modelbuilder/readme.md
Builds on https://github.com/dotnet/machinelearning-samples/pull/419
> Modify Model Builder download/install text

- samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/README.md
- samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/SentimentAnalysis/SentimentAnalysisConsoleApp/Program.cs
Simplified sample code and updated README to work with [Try .NET](https://github.com/dotnet/try)
> Make Sentiment Analysis sample work with Try .NET

- samples/csharp/end-to-end-apps/ScalableSentimentAnalysisBlazorWebApp/BlazorSentimentAnalysis.Client/BlazorSentimentAnalysis.Client.csproj
- samples/csharp/end-to-end-apps/ScalableSentimentAnalysisBlazorWebApp/BlazorSentimentAnalysis.Server/BlazorSentimentAnalysis.Server.csproj
- samples/csharp/end-to-end-apps/ScalableSentimentAnalysisBlazorWebApp/BlazorSentimentAnalysis.Server/Startup.cs
- samples/csharp/end-to-end-apps/ScalableSentimentAnalysisBlazorWebApp/README.md
Core 3 preview 6 dropped this `app.UseBlazor<Client.Startup>(); ` resulting in compile errors. I have updated them.
> Update to Core 3 Preview 6

- samples/csharp/getting-started/Clustering_CustomerSegmentation/README.md
> Update Readme.md typo

- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/Program.cs
- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/YoloParser/YoloOutputParser.cs
Renamed `YoloWinMlParser` to `YoloOutputParser`
> Renamed YOLO output parser class

- samples/csharp/end-to-end-apps/Regression-SalesForecast/src/eShopDashboard/package-lock.json
-Updated lodashtemp to version 4.5.0
> Fix security vulnerability

- samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/SentimentAnalysis/SentimentAnalysisConsoleApp/Program.cs
-Removed regions in sentiment analysis code to simplify
> Removed sentiment analysis regions

- samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/SentimentAnalysis/SentimentAnalysisConsoleApp/Program.cs
Include a clearly non-toxic sentiment that is easier for analysis by first-time users. Also fixed small typo in comment.
> Small Sentiment Analysis Changes

- samples/csharp/end-to-end-apps/DeepLearning_ImageClassification_TensorFlow/README.md
Added tips for using a custom model, small formatting changes
> Updated TensorFlow readme

- samples/csharp/v1.3.1-All-Samples.sln
Add the 2 newest samples (model explainability and Azure functions) to global 1.3.1 solution
> Add samples solution

- README.md
-Add new razor model builder sample to main readme
-Update order and some title wording of samples on main readme
> Add razor sample to homepage

- samples/csharp/end-to-end-apps/ObjectDetection-Onnx/README.md
Added troubleshooting steps for ASP.NET Core App
> Troubleshoot Onnx E2E ASP.NET Core App

- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/README.md
Added link to ONNX object detection tutorial on Microsoft Docs site to sample README
> Added link to Docs ONNX tutorial

- samples/csharp/end-to-end-apps/ScalableMLModelOnAzureFunction/README.md
- samples/csharp/end-to-end-apps/ScalableMLModelOnAzureFunction/SentimentAnalysisFunctionsApp/AnalyzeSentiment.cs
- samples/csharp/end-to-end-apps/ScalableMLModelOnAzureFunction/SentimentAnalysisFunctionsApp/Startup.cs
Added code for model reload in Azure Functions sample.
> Model reload in Azure Functions Sample

- samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/README.md
Linking from sample to tutorial on Docs site.
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning
> Added reference to Image Classification tutorial on Docs site.

- samples/csharp/end-to-end-apps/ScalableMLModelOnAzureFunction/SentimentAnalysisFunctionsApp/SentimentAnalysisFunctionsApp.csproj
- samples/csharp/end-to-end-apps/ScalableMLModelOnAzureFunction/SentimentAnalysisFunctionsApp/Startup.cs
Updated sample to run on Azure
- Depending on the environment (Dev=Local/Prod=Azure), set the path in the `Startup` class where the model is stored.
> Update Azure Functions sample to run on Azure

- samples/modelbuilder/MulticlassClassification_RestaurantViolations/README.md
Add link to Multiclass Model Builder Docs tutorial in sample
> Add link to Multiclass Model Builder Docs tutorial

- samples/csharp/getting-started/MulticlassClassification_AutoML/MNIST/Program.cs
> MNIST Auto ML - Add prefeaturizer for predictable Score[] ordering

- samples/csharp/getting-started/Forecasting_BikeSharingDemand/README.md
Adding more details about the pipeline to time series forecasting sample.
> Update Time Series Forecasting Sample README

- samples/csharp/getting-started/Forecasting_BikeSharingDemand/BikeDemandForecasting/BikeDemandForecasting.csproj
Only updates to `csproj` were done
> Updated Bike Sharing Forecasting sample to 1.4

- modelbuilder/readme.md
-add .txt to supported dataset file type
> update Model Builder documentation

- samples/csharp/end-to-end-apps/AnomalyDetection-Sales/SpikeDetectionE2EApp/SpikeDetection.ModelTrainer/Program.cs
> Contributing: Fix a typo

- samples/csharp/getting-started/Regression_TaxiFarePrediction/TaxiFarePrediction/TaxiFarePredictionConsoleApp/Program.cs
Fix Comment Typo: repeteable > repeatable
> Fix Comment Typo: repeteable > repeatable

- samples/csharp/end-to-end-apps/ScalableMLModelOnAzureFunction/SentimentAnalysisFunctionsApp/SentimentAnalysisFunctionsApp.csproj
> Updated AzFunctions SDK Version

- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/ObjectDetection.csproj
Updated sample to match dotnet/docs#18903 changes
> Updated ONNX Getting Started Sample to to v1.5

- samples/csharp/getting-started/BinaryClassification_SpamDetection/SpamDetectionConsoleApp/Program.cs
Fixes #710 
Removed and extra lp norm and added norm to the FeaturizeText options object, and set it to NormFunction.L2.
> removed extra lpnorm

- samples/Directory.Build.props
- samples/csharp/end-to-end-apps/ObjectDetection-Onnx/README.md
- samples/csharp/getting-started/AnomalyDetection_CreditCardFraudDetection/CreditCardFraudDetection.Predictor/CreditCardFraudDetection.Predictor.csproj
- samples/csharp/getting-started/AnomalyDetection_CreditCardFraudDetection/CreditCardFraudDetection.Trainer/CreditCardFraudDetection.Trainer.csproj
- samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/DeepLearning_ImageClassification/DeepLearning_ImageClassification.csproj
- samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/README.md
- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/ObjectDetectionConsoleApp/ObjectDetection.csproj
- samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx/README.md
- samples/csharp/getting-started/Forecasting_BikeSharingDemand/BikeDemandForecasting/BikeDemandForecasting.csproj
- samples/csharp/getting-started/Forecasting_BikeSharingDemand/README.md
Updated non Model Builder tutorial samples to .NET 5 and 1.6.0.
- BikeDemandForecasting
- Update to 1.6.0
- Update to .NET 5
- DeepLearning_ObjectDetection_Onnx
- Update to 1.6.0 and ONNX Runtime 1.8.1
- Update to .NET 5
- DeepLearning_ImageClassification_Binary
- Update to .NET 5
> Update tutorial samples to 1.6.0

- samples/csharp/end-to-end-apps/ScalableMLModelOnAzureFunction/README.md
- samples/csharp/getting-started/AnomalyDetection_PhoneCalls/README.md
- samples/modelbuilder/BinaryClassification_Sentiment_Razor/README.md
- samples/modelbuilder/ImageClassification_Azure_LandUse/README.md
- samples/modelbuilder/MulticlassClassification_RestaurantViolations/README.md
- samples/modelbuilder/ObjectDetection_StopSigns/README.md
Update and add metadata to samples with tutorials to show up on Microsoft Docs samples catalog.
> Update samples metadata

- samples/csharp/end-to-end-apps/ScalableMLModelOnAzureFunction/SentimentAnalysisFunctionsApp/AnalyzeSentiment.cs
- samples/csharp/end-to-end-apps/ScalableMLModelOnAzureFunction/SentimentAnalysisFunctionsApp/SentimentAnalysisFunctionsApp.csproj
- samples/csharp/end-to-end-apps/ScalableMLModelOnAzureFunction/SentimentAnalysisFunctionsApp/Startup.cs
- samples/csharp/end-to-end-apps/ScalableMLModelOnAzureFunction/SentimentAnalysisFunctionsApp/host.json
- samples/csharp/end-to-end-apps/ScalableMLModelOnAzureFunction/SentimentAnalysisFunctionsApp/local.settings.json
Update Azure Function Sample App
Related to dotnet/docs#32973
> Update Az Fn Sample App

- samples/csharp/end-to-end-apps/Forecasting-Sales/src/eShopDashboard/Startup.cs
- samples/modelbuilder/MatrixFactorization_MovieRecommendation/MovieRecommender_WebApi/Program.cs
See [this internal issue](https://github.com/dotnet/aspnetcore-internal/issues/4522)
Fixes #1024
> Use SwaggerUI in development environment only
